"""
app/services/mock_data.py
USE_MOCK=true 时替代高德 API，返回 10 条光谷附近测试餐厅数据
格式与 data_cleaner 输出的 Restaurant.to_dict() 完全一致
"""

_MOCK_RESTAURANTS = [
    {
        "restaurant_id": "R001",
        "name": "老成都川菜馆",
        "category": "中餐厅;川菜",
        "address": "光谷步行街A座101",
        "latitude": 30.532,
        "longitude": 114.362,
        "rating": 4.6,
        "avg_price": 45.0,
        "distance_m": 320,
    },
    {
        "restaurant_id": "R002",
        "name": "渝味火锅城",
        "category": "中餐厅;火锅",
        "address": "关山大道88号",
        "latitude": 30.528,
        "longitude": 114.358,
        "rating": 4.4,
        "avg_price": 80.0,
        "distance_m": 750,
    },
    {
        "restaurant_id": "R003",
        "name": "粤香楼茶餐厅",
        "category": "中餐厅;粤菜",
        "address": "光谷广场B栋203",
        "latitude": 30.535,
        "longitude": 114.365,
        "rating": 4.5,
        "avg_price": 65.0,
        "distance_m": 480,
    },
    {
        "restaurant_id": "R004",
        "name": "湘情烤鱼",
        "category": "中餐厅;湘菜",
        "address": "珞喻路12号",
        "latitude": 30.527,
        "longitude": 114.370,
        "rating": 4.3,
        "avg_price": 55.0,
        "distance_m": 900,
    },
    {
        "restaurant_id": "R005",
        "name": "日式拉面馆",
        "category": "日本料理;拉面",
        "address": "光谷国际C区15",
        "latitude": 30.533,
        "longitude": 114.356,
        "rating": 4.7,
        "avg_price": 50.0,
        "distance_m": 260,
    },
    {
        "restaurant_id": "R006",
        "name": "麦辣鸡排快餐",
        "category": "快餐;炸鸡",
        "address": "光谷大道102号",
        "latitude": 30.530,
        "longitude": 114.363,
        "rating": 4.0,
        "avg_price": 25.0,
        "distance_m": 150,
    },
    {
        "restaurant_id": "R007",
        "name": "米粉世家",
        "category": "中餐厅;米粉",
        "address": "高新四路5号",
        "latitude": 30.526,
        "longitude": 114.368,
        "rating": 4.2,
        "avg_price": 18.0,
        "distance_m": 600,
    },
    {
        "restaurant_id": "R008",
        "name": "韩式烤肉坊",
        "category": "韩国料理;烤肉",
        "address": "软件园二路33号",
        "latitude": 30.536,
        "longitude": 114.361,
        "rating": 4.5,
        "avg_price": 90.0,
        "distance_m": 820,
    },
    {
        "restaurant_id": "R009",
        "name": "素食轩",
        "category": "中餐厅;素食",
        "address": "光谷创业街8号",
        "latitude": 30.531,
        "longitude": 114.367,
        "rating": 4.1,
        "avg_price": 35.0,
        "distance_m": 410,
    },
    {
        "restaurant_id": "R010",
        "name": "西式牛排馆",
        "category": "西餐;牛排",
        "address": "民族大道19号",
        "latitude": 30.534,
        "longitude": 114.354,
        "rating": 4.8,
        "avg_price": 150.0,
        "distance_m": 560,
    },
]


def get_mock_restaurants(max_count: int = 20) -> list[dict]:
    return _MOCK_RESTAURANTS[:max_count]
